---
name: Test Deployment Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test deployment job
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Hello world
        run: |
          echo "Hello world"
